# Generated by Django 5.0.6 on 2024-05-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="emergency_contact_phone",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="emergency_contact_relationship",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="immunization_records",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="insurance_expiry_date",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="insurance_number",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="insurance_provider",
        ),
        migrations.AddField(
            model_name="patient",
            name="InstagramId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="facebookId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
