# Generated by Django 5.0.6 on 2024-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_remove_patient_emergency_contact_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="Revisit",
            field=models.IntegerField(default=7),
        ),
    ]
