# Generated by Django 5.0.6 on 2024-05-22 15:46

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0001_initial"),
        ("patients", "0003_patient_revisit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="family_medical_history",
        ),
        migrations.AddField(
            model_name="patient",
            name="consultant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="doctors.normalemployee",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="diagnosis",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="allergies"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="patient_complaint",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="allergies"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="photos",
            field=models.ImageField(blank=True, null=True, upload_to="upload/patient/"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="current_medication",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="current_medication"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="medical_history"
            ),
        ),
    ]
