# Generated by Django 5.0.6 on 2024-05-22 15:47

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_remove_patient_allergies_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="photos",
            new_name="photos1",
        ),
        migrations.AddField(
            model_name="patient",
            name="photos2",
            field=models.ImageField(blank=True, null=True, upload_to="upload/patient/"),
        ),
        migrations.AddField(
            model_name="patient",
            name="photos3",
            field=models.ImageField(blank=True, null=True, upload_to="upload/patient/"),
        ),
        migrations.AddField(
            model_name="patient",
            name="photos4",
            field=models.ImageField(blank=True, null=True, upload_to="upload/patient/"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="diagnosis",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="diagnosis"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_complaint",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="patient_complaint"
            ),
        ),
    ]
