# Generated by Django 5.0.6 on 2024-05-22 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_rename_photos_patient_photos1_patient_photos2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="notes",
            new_name="Further_Investigation",
        ),
    ]
