# Generated by Django 5.0.6 on 2024-05-22 15:52

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_rename_notes_patient_further_investigation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="current_medication",
        ),
        migrations.AddField(
            model_name="patient",
            name="Treatement",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Treatment"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="diagnosis",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Diagnosis"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medical_history",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Medical History"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_complaint",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Patient Complaint"
            ),
        ),
    ]
