# Generated by Django 5.0.6 on 2024-05-22 15:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "patients",
            "0007_remove_patient_current_medication_patient_treatement_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="Further_Investigation",
        ),
        migrations.AddField(
            model_name="patient",
            name="Investigation",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Investigation"
            ),
        ),
    ]
