# Generated by Django 5.0.6 on 2024-05-21 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('id_proof_type', models.CharField(choices=[('Nagrikta', 'Nagrikta'), ('Passport', 'Passport'), ("Driver's License", "Driver's License"), ('Voter ID', 'Voter ID')], max_length=50)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('id_proof_document', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry_date', models.DateField()),
                ('specialization', models.CharField(max_length=100)),
                ('qualifications', models.TextField()),
                ('years_of_experience', models.IntegerField()),
                ('current_hospital', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_hospitals', models.TextField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_days', models.CharField(help_text='Comma-separated list of available days (e.g., Monday, Wednesday, Friday)', max_length=100)),
                ('available_from_time', models.TimeField()),
                ('available_to_time', models.TimeField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('doctor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doctors.doctor')),
                ('certificate_1', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_2', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_3', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_4', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_5', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_6', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_7', models.FileField(blank=True, null=True, upload_to='certificates/')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
            bases=('doctors.doctor',),
        ),
        migrations.CreateModel(
            name='NormalEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_proof_type', models.CharField(choices=[('Nagrikta', 'Nagrikta'), ('Passport', 'Passport'), ("Driver's License", "Driver's License"), ('Voter ID', 'Voter ID')], max_length=50)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('id_proof_document', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='doctors.normalemployee')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
